# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r:
  - release
  - devel
addons:
  apt:
    packages:
      - libxml2-dev
script:
  - cd ../
  - R CMD build myRpackage
  - R CMD check myRpackage_*.tar.gz --no-build-vignettes --no-manual
