# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r:
  - release
  - devel
addons:
  apt:
    packages:
      - libxml2-dev
warnings_are_errors: false
script:
  - R CMD check . --no-build-vignettes --no-manual
